import type { EffectConfig } from '@/effects/config';

// The hand-tuned settings the prototype shipped with (its defaults.js).
export const defaultPreset: Partial<EffectConfig> = {
    duration: 7,
    stagger: 2.16,
    density: 0.47,
    maxRays: 1,
    autoplay: true,
    whiteDur: 0.05,
    colorDur: 0.45,
    texDur: 0.8,
    hold: 0.18,
    whiteLevel: 1,
    colorSat: 1.15,
    colorBoost: 1.15,
    dotSize: 1,
    dotPulse: 2,
    dotStart: 0.4,
    dotStagger: 0.15,
    dotGrow: 0.08,
    logoScale2: 0.13,
    logoX2: 0.235,
    logoY2: 0.07,
    moveDur: 1.5,
    moveStagger: 0.5,
    moveDelay: 0.2,
    moveFade: 0.35,
    newLinesBy: 0.5,
    autoMove: true,
    logoScale: 0.72,
    logoX: 0.5,
    logoY: 0.5,
    texScale: 1.15,
    lineWidth: 15.5,
    lineH: 0,
    lineS: 0,
    lineB: 100,
    glow: 0.76,
    glowWidth: 4,
    glowLayers: 2,
    glowFalloff: 2,
    glowHue: 0,
    bloom: 1.48,
    bloomRadius: 1.5,
    bloomIdle: 0.49,
    trail: 0.55,
    trailBias: 0.8,
    trailHue: 0,
    trailDim: 0.25,
    trailFade: 0.3,
    taper: 0.6,
};
